### ISSUE TITLE
mysql view table dropper is not yet merged on master src

### ISSUE THREAD

**Issue by jericopulvera** [spatie/laravel-migrate-fresh#47] opened 2017-06-29 06:00 UTC

**Comment by freekmurze** [comment] 2017-06-29 19:14
Could you describe in more detail what the problem is?

**Comment by freekmurze** [comment] 2017-07-05 08:04
Closing this for now. Feel free to reopen to point me to pieces of code that are not in the latest release.

**Closed as completed by freekmurze** 2017-07-05 08:04 UTC

**Comment by jericopulvera** [comment] 2017-07-06 11:33
I have a view in my database and I use the migrate:fresh command from the latest release.

I get an error that view cannot be dropped.

I use mysql database.

I saw a fix on #28 and it has been merged.

But i Looked at the src on the master branch and the code is not there yet.
